blog/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf.urls.static import static
from SBlog.views import ScribbleView, HomeView, BlogListView, PicView, BlogDetailView
from sign.views import LoginView, LogoutView, SignupView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    # url(r'^blog/', include('blog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'home/$', HomeView.as_view(), name='home'),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'signup/$', SignupView.as_view(), name='signup'),
    url(r'blogs/$', BlogListView.as_view(), name='blogs'),
    url(r'read_blog/?', BlogDetailView.as_view(), name='read_blog'),
    url(r'scribble/$', ScribbleView.as_view(), name='scribble'),
    url(r'pic/$', PicView.as_view(), name='pic'),
    url(r'home/comments$', 'SBlog.views.get_comments', name='get_comments'),
    url(r'like$', 'SBlog.views.add_like', name='add_like'),
    url(r'home/post_comments$', 'SBlog.views.post_comments', name='post_comments'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/models.py
from django.db import models

# Create your models here.

sign/forms.py
__author__ = 'shinoymm'
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=256, min_length=4)
    password = forms.CharField(max_length=256, min_length=4, widget=forms.PasswordInput)


class SignupForm(forms.Form):
    s_username = forms.CharField(max_length=256, min_length=4)
    s_mail = forms.EmailField()
    s_password = forms.CharField(max_length=256, min_length=4, widget=forms.PasswordInput)
    s_password2 = forms.CharField(max_length=256, min_length=4, widget=forms.PasswordInput)

sign/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from django.views.generic.edit import FormView, View
from sign.forms import LoginForm, SignupForm


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'sign/login.html'
    success_url = 'home/'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['signup'] = SignupForm
        context['login'] = LoginForm
        return context

    def get_success_url(self):
        return self.request.GET.get('next', '/')

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            if user.is_active:
                login(self.request, user)
                return HttpResponseRedirect(self.get_success_url())
            else:
                context = self.get_context_data(form=form)
                context['errors'] = 'This user is Inactive'
                return self.render_to_response(context)
        else:
            context = self.get_context_data(form=form)
            context['errors'] = 'LOGIN FAILED !!!'
            return self.render_to_response(context)


class LogoutView(View):
    success_url = 'home/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(self.success_url)
    
    
class SignupView(LoginView):
    form_class = SignupForm

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        context['errors'] = []
        if User.objects.filter(username=form.cleaned_data['s_username']).exists():
            context['errors'].append('A User with this username exists !!!')
        elif User.objects.filter(email=form.cleaned_data['s_username']).exists():
            context['errors'].append('A User with this email exists !!!')
        else:
            user = User.objects.create_user(form.cleaned_data['s_username'], form.cleaned_data['s_mail'], form.cleaned_data['s_password'])
            user.save()
            user = authenticate(username=form.cleaned_data['s_username'], password=form.cleaned_data['s_password'])
            if user:
                login(self.request, user)
                return HttpResponseRedirect(self.get_success_url())
            else:
                context = self.get_context_data(form=form)
                context['errors'] = 'REGISTRATION FAILED !!!'
                return self.render_to_response(context)

        return self.render_to_response(context)

blog/templates/sign/login.html
{% extends 'layout.html' %}
  {% block content %}
    {% if errors %}
      <div class="row">
        <div class="col s12">
          <div class="card-panel red lighten-3">
            <span class="white-text">{{errors}}</span>
          </div>
        </div>
      </div>
    {% endif %}
    <form action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <div class="row input-field">
        <div class="col s12">
          {{login.username}}<div class="red-text">{{form.username.errors}}</div>
          <label for="id_username">Username/Mail</label>
        </div>
      </div>
      <div class="row input-field">
        <div class="col s12">
          {{login.password}}<div class="red-text">{{form.password.errors}}</div>
          <label for="id_password">Password</label>
        </div>
      </div>
      <!--<input type="submit">-->
      <button class="btn waves-effect waves-light btn-large" type="submit">Login</button>
    </form>

<hr>

  <div class="row">
  <div class="card centered col s8 offset-s2 red darken-4 z-depth-2">
    <div class="card-content">
    <form action="{% url 'signup' %}" method="post">
      {% csrf_token %}
      <div class="row input-field">
        <div class="col s12">
          {{signup.s_username}}<div class="red-text">{{form.s_username.errors}}</div>
          <label for="id_s_username">Username/Mail</label>
        </div>
      </div>
      <div class="row input-field">
        <div class="col s12">
          {{signup.s_mail}}<div class="red-text">{{form.s_mail.errors}}</div>
          <label for="id_s_username">Mail</label>
        </div>
      </div>
      <div class="row input-field">
        <div class="col s12">
          {{signup.s_password}}<div class="red-text">{{form.s_password.errors}}</div>
          <label for="id_s_password">Password</label>
        </div>
      </div>
      <div class="row input-field">
        <div class="col s12">
          {{signup.s_password2}}<div class="red-text">{{form.s_password2.errors}}</div>
          <label for="id_s_password">Password Again</label>
        </div>
      </div>
      <button class="btn waves-effect waves-light btn-large" type="submit">Sign in</button>
    </form>
    </div>
    </div>
    </div>
  {% endblock %}